# Netlify 部署配置檔案
# StreetVoice sv.link 批次短網址生成器

[build]
  publish = "."
  command = ""

[build.environment]
  PYTHON_VERSION = "3.8"

[functions]
  directory = "netlify/functions"
  timeout = 30
  memory = 128

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, X-API-Key"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"